# Generated by Django 4.0.4 on 2022-05-30 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_drink', models.CharField(max_length=100)),
                ('desc_drink', models.CharField(max_length=100)),
                ('alcohol_type', models.IntegerField(choices=[(1, 'Vodka'), (2, 'Whisky'), (3, 'Gin'), (4, 'Tequila'), (5, 'Rum')])),
                ('pub_date', models.DateTimeField(verbose_name='Date Published')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ingredient', models.CharField(max_length=100)),
                ('drinks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shaker.drinks')),
            ],
        ),
    ]
