# Generated by Django 4.0.4 on 2022-05-30 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shaker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drinks',
            name='alcohol_type',
            field=models.IntegerField(choices=[(1, 'Vodka'), (2, 'Whisky'), (3, 'Gin'), (4, 'Tequila'), (5, 'Rum'), (6, 'Rakija')]),
        ),
    ]
