# Generated by Django 4.0.4 on 2022-06-05 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shaker', '0002_alter_drinks_alcohol_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drinks',
            name='pub_date',
        ),
    ]
