# Generated by Django 4.0.4 on 2022-06-06 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shaker', '0003_remove_drinks_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='drinks',
            name='image_drink',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
